### PR TITLE
added extern to fix compilation on gcc 10

### PR DESCRIPTION
**Pull request by ARibecaJob**
added extern to fix compilation on gcc 10

### CODE REVIEW

**Comment by gilbertozp** [comment]
Compilation failing with error (from running make):
```
Building /home/user/bin/oneflux/ure...
cd /home/user/dev/ONEFlux/oneflux_steps/ure/src/ ;\
gcc -O3 -w -c dataset.c main.c ;\
gcc -O3 dataset.o main.o /home/user/dev/ONEFlux/oneflux_steps/common/common.o -w -lm -o /home/user/bin/oneflux/ure
/usr/bin/ld: main.o:(.data.rel.local+0x0): multiple definition of `authors_suffix'; dataset.o:(.bss+0x0): first defined here
/usr/bin/ld: main.o:(.data.rel.local+0x20): multiple definition of `types_suffix'; dataset.o:(.bss+0x20): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:174: /home/user/bin/oneflux/ure] Error 1
```

**Comment by gilbertozp** [comment]
@ARibecaJob , when ready, please change pull request to merge into `main` branch, instead of creating new `24-update-c-code-base-to-comply-with-new-enforcement-of-single-declaration-of-universal-variables` (this new one is ok on your fork, but the PR should point to main in the FLUXNET/ONEFlux repo).

Thanks!

**Comment by ARibecaJob** [comment]
> Compilation failing with error (from running make):
> 
> ```
> Building /home/user/bin/oneflux/ure...
> cd /home/user/dev/ONEFlux/oneflux_steps/ure/src/ ;\
> gcc -O3 -w -c dataset.c main.c ;\
> gcc -O3 dataset.o main.o /home/user/dev/ONEFlux/oneflux_steps/common/common.o -w -lm -o /home/user/bin/oneflux/ure
> /usr/bin/ld: main.o:(.data.rel.local+0x0): multiple definition of `authors_suffix'; dataset.o:(.bss+0x0): first defined here
> /usr/bin/ld: main.o:(.data.rel.local+0x20): multiple definition of `types_suffix'; dataset.o:(.bss+0x20): first defined here
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:174: /home/user/bin/oneflux/ure] Error 1
> ```

Hi,

please give me a little bit of time to check compilation on Gcc X and Gcc v10.
I've checked only on gcc v10.

Alessio

**Comment by gilbertozp** [comment]
Thank you, @ARibecaJob; I started from a fresh repo, so it's probably not related to older builds. These might be GCC 11 specific, this is the version I ran.

**Comment by ARibecaJob** [comment]
> Member

Hi,

checked with gcc 11. No errors.
Are you sure that your using my PR ?

**Comment by gilbertozp** [comment]
Thank you, Alessio. That was my bad, the version I was testing was indeed not from your PR. It is now the correct one, the compile step is working, and tests with data are running. I will merge this as soon as these are finished.

**Review by gilbertozp — APPROVED** [review]
Compile tests with gcc (Red Hat) version 8.5.0 and gcc (Spark) versions 10.5.0, 11.4.0, 13.2.0; execution tests with gcc (Spark) 10.5.0

**Pull request merged**
